#!/usr/bin/env bash

set -euo pipefail

main() {
    build

    d=test_dir
    tests=()
    tests+=("bash/hashdir.sh $d")
    tests+=("python/hashdir.py $d")
    tests+=("rust/target/release/hashdir $d")
    tests+=("go/go $d")
    tests+=("$(find haskell -executable -name hashdir -type f) $d")

    run_tests "${tests[@]}"
    run_hyperfine "${tests[@]}"
}

info() {
    if [[ -t 1 ]]; then
        echo -e "\e[36m:: $*\e[0m"
    else
        echo "$*"
    fi
}

build() {
    info "building"
    ( cd rust && cargo build --release --quiet )
    ( cd go && go build . ; )
    ( cd haskell && cabal build ; )
    # ( cd nim && nimble build --silent ; )
}

run_tests() {
    info "testing for correctness"
    for cmd in "$@"; do
        info "$cmd"
        $cmd
    done
}

run_hyperfine() {
    info "benchmarking"
    hyperfine "$@"
}

main "$@"
