#!/usr/bin/env bash

set -euo pipefail

main() {
    build

    d=test_dir
    tests=()
    tests+=("bash/hashdir.sh $d")
    tests+=("python/hashdir.py $d")
    tests+=("rust/target/release/hashdir $d")
    tests+=("go/go $d")

    run_tests "${tests[@]}"
    run_hyperfine "${tests[@]}"
}


build() {
    echo ":: building"
    ( cd rust && cargo build --release --quiet )
    ( cd go && go build . ; )
    # ( cd nim && nimble build --silent ; )
}

run_tests() {
    echo ":: testing for correctness"
    for cmd in "$@"; do
        $cmd
    done
}

run_hyperfine() {
    echo ":: benchmarking"
    hyperfine "$@"
}

main "$@"
