[package]
name = "hashdir"
version = "0.1.0"
authors = ["Preston Hunt <me@prestonhunt.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
walkdir = "2"
ring = ""
hex = ""
